"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def fib(n):
    a, b = 0, 1
    while b < n:
        print(b)
        a, b = b, a+b


#assert fib(10) == (1, 1, 2, 3, 5, 8)
#assert fib(10) == 1
#assert fib(10) == 2
#assert fib(10) == 3
#assert fib(10) == 5
#assert fib(10) == 8


"""In [57]: def fib(n):
    ...:     a, b = 0, 1
    ...:     while b < n:
    ...:         lst = str(b)
    ...:         print(list(lst))
    ...:         a, b = b, a+b
    ...:         #muda = str(b) 
    ...:         #listapares = list(muda)
    ...:         
    ...: #pares = listapares[::2]
    ...:         #print (b)
    ...:         

In [58]: fib(10)
['1']
['1']
['2']
['3']
['5']
['8']


"""